SELECT CASE 
            WHEN ST.MARKS>=70 
               THEN ST.NAME 
               ELSE NULL 
       END as NAME,GR.GRADE,ST.MARKS  FROM STUDENTS ST, GRADES GR
WHERE ST.MARKS>=GR.MIN_MARK 
AND ST.MARKS<=GR.MAX_MARK
ORDER BY GR.GRADE DESC,ST.NAME ASC,ST.MARKS DESC;
