SELECT H.HACKER_ID ,H.NAME
FROM Hackers H, Difficulty D, Challenges C, Submissions S
WHERE S.CHALLENGE_ID=C.CHALLENGE_ID
AND C.DIFFICULTY_LEVEL=D.DIFFICULTY_LEVEL
AND S.SCORE=D.SCORE
AND S.HACKER_ID=H.HACKER_ID
GROUP BY H.HACKER_ID ,H.NAME
HAVING COUNT(S.CHALLENGE_ID) > 1
ORDER BY COUNT(S.CHALLENGE_ID) DESC,H.HACKER_ID;